# Generated by Django 5.0.3 on 2024-03-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aunts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('total_fruit', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='course/aunts/')),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fruit/fruits/')),
                ('price', models.FloatField()),
                ('rayting', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[("Ko'rinmasin", "Ko'rinmasin"), ("Ko'rinsin", "ko'rinsin")], default="Ko'rinsin", max_length=20)),
                ('aunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.aunts')),
            ],
        ),
    ]
